import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

const herbs = [
  {
    name: 'Arnica Flower', spanishName: 'Árnica', latinName: 'Arnica montana',
    description: 'A powerful anti-inflammatory herb traditionally used for bruises, muscle soreness, and pain relief. Often used topically for healing.',
    pricePerOunce: 9, inventoryOunces: 16,
    tags: ['pain relief', 'inflammation', 'muscle tension', 'recovery', 'joint support'],
    energetics: 'Warming', taste: 'Bitter, slightly acrid', partsUsed: 'Flowers',
    contraindications: 'Not for internal use. External use only. Avoid on broken skin.', featured: false, active: true,
  },
  {
    name: 'Ashwagandha', spanishName: 'Ashwagandha', latinName: 'Withania somnifera',
    description: 'A premier adaptogenic root that helps the body resist stress, supports adrenal health, and promotes vitality and stamina.',
    pricePerOunce: 6, inventoryOunces: 32,
    tags: ['adaptogen', 'stress', 'adrenal support', 'energy', 'fatigue', 'vitality', 'stamina', 'anxiety', 'nervous system', 'immune', 'libido'],
    energetics: 'Warming, grounding', taste: 'Earthy, bitter, slightly sweet', partsUsed: 'Root',
    contraindications: 'Avoid during pregnancy. May interact with thyroid medications.', featured: true, active: true,
  },
  {
    name: 'Alfalfa', spanishName: 'Alfalfa', latinName: 'Medicago sativa',
    description: 'A deeply nutritive herb rich in vitamins and minerals. Excellent as a daily tonic for overall nourishment and vitality.',
    pricePerOunce: 6, inventoryOunces: 24,
    tags: ['minerals', 'nutritive', 'nourishing', 'tonic', 'energy', 'vitality', 'detox', 'blood purifier'],
    energetics: 'Neutral to cooling', taste: 'Mild, grassy', partsUsed: 'Leaf',
    contraindications: 'Avoid in autoimmune conditions. May interact with blood thinners.', featured: false, active: true,
  },
  {
    name: 'Black Cohosh Root', spanishName: 'Cohosh Negro', latinName: 'Actaea racemosa',
    description: 'A powerful women\'s herb used for centuries to support hormonal balance, ease menopausal symptoms, and relieve menstrual cramps.',
    pricePerOunce: 8, inventoryOunces: 16,
    tags: ['women hormones', 'menopause', 'perimenopause', 'cramps', 'cycle balance', 'estrogen balance', 'pms', 'pain relief'],
    energetics: 'Cooling', taste: 'Bitter, acrid', partsUsed: 'Root',
    contraindications: 'Avoid during pregnancy. Not for long-term use over 6 months.', featured: false, active: true,
  },
  {
    name: 'Black Walnut Hull', spanishName: 'Cáscara de Nuez Negra', latinName: 'Juglans nigra',
    description: 'A potent antiparasitic and antifungal herb. Used for internal cleansing, candida overgrowth, and eliminating parasites.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['parasite', 'candida', 'antifungal', 'detox', 'cleanse', 'antimicrobial', 'colon cleanse'],
    energetics: 'Cooling, drying', taste: 'Very bitter, astringent', partsUsed: 'Hull',
    contraindications: 'Avoid during pregnancy. Do not use long-term.', featured: false, active: true,
  },
  {
    name: 'Blue Vervain', spanishName: 'Verbena Azul', latinName: 'Verbena hastata',
    description: 'A premier nervine for those who hold tension in the body and mind. Releases rigidity, eases anxiety, and supports emotional release.',
    pricePerOunce: 8, inventoryOunces: 16,
    tags: ['nervine', 'stress', 'anxiety', 'tension', 'nervous system', 'emotional release', 'burnout', 'overwhelm', 'trauma support', 'grounding'],
    energetics: 'Cooling, bitter', taste: 'Very bitter', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Burdock Root', spanishName: 'Raíz de Bardana', latinName: 'Arctium lappa',
    description: 'A deeply cleansing root that supports the liver, kidneys, and lymphatic system. Excellent for skin health and blood purification.',
    pricePerOunce: 4, inventoryOunces: 32,
    tags: ['detox', 'liver', 'kidney', 'lymphatic', 'lymph support', 'skin', 'acne', 'blood purifier', 'alterative', 'digestive bitters'],
    energetics: 'Cooling, moistening', taste: 'Earthy, slightly sweet, bitter', partsUsed: 'Root',
    contraindications: 'May interact with blood thinners and diabetes medications.', featured: false, active: true,
  },
  {
    name: 'Calendula', spanishName: 'Caléndula', latinName: 'Calendula officinalis',
    description: 'A gentle, healing flower with powerful anti-inflammatory and antimicrobial properties. Soothes the digestive tract and supports skin healing.',
    pricePerOunce: 5, inventoryOunces: 24,
    tags: ['skin', 'inflammation', 'gut repair', 'lymphatic', 'antimicrobial', 'stomach soothing', 'eczema', 'digestive bitters', 'lymph support'],
    energetics: 'Warming, slightly drying', taste: 'Slightly bitter, resinous, floral', partsUsed: 'Flowers',
    contraindications: 'Avoid during pregnancy in large amounts.', featured: true, active: true,
  },
  {
    name: 'Catnip', spanishName: 'Hierba Gatera', latinName: 'Nepeta cataria',
    description: 'A gentle nervine and digestive herb. Wonderful for calming nerves, easing gas and colic, and supporting restful sleep.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['nervine', 'calming', 'sleep', 'digestion', 'gas', 'bloating', 'anxiety', 'stress', 'relaxation', 'children safe'],
    energetics: 'Cooling', taste: 'Minty, slightly bitter', partsUsed: 'Aerial parts',
    contraindications: 'Avoid large amounts during pregnancy.', featured: false, active: true,
  },
  {
    name: "Cat's Claw", spanishName: 'Uña de Gato', latinName: 'Uncaria tomentosa',
    description: 'A powerful immune-modulating and anti-inflammatory herb from the Amazon. Supports joint health and overall immune defense.',
    pricePerOunce: 4, inventoryOunces: 16,
    tags: ['immune', 'inflammation', 'joint support', 'arthritis', 'antiviral', 'antimicrobial', 'detox'],
    energetics: 'Cooling', taste: 'Bitter, astringent', partsUsed: 'Bark, root',
    contraindications: 'Avoid during pregnancy. May interact with blood pressure medications.', featured: false, active: true,
  },
  {
    name: 'Chamomile', spanishName: 'Manzanilla', latinName: 'Matricaria chamomilla',
    description: 'One of the most beloved herbs in the world. Deeply calming for the nervous system and digestive tract. Perfect for stress, anxiety, and sleep.',
    pricePerOunce: 7, inventoryOunces: 32,
    tags: ['nervine', 'calming', 'sleep', 'digestion', 'anxiety', 'stress', 'stomach soothing', 'relaxation', 'inflammation', 'bedtime', 'gas', 'bloating'],
    energetics: 'Slightly warming', taste: 'Sweet, floral, slightly bitter', partsUsed: 'Flowers',
    contraindications: 'Possible allergy if sensitive to ragweed family.', featured: true, active: true,
  },
  {
    name: 'Chaste Berries', spanishName: 'Bayas de Sauzgatillo', latinName: 'Vitex agnus-castus',
    description: 'A premier herb for hormonal balance in women. Regulates the menstrual cycle, eases PMS, and supports progesterone balance.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['women hormones', 'pms', 'cycle balance', 'progesterone support', 'irregular cycle', 'fertility', 'menopause', 'perimenopause'],
    energetics: 'Cooling, drying', taste: 'Peppery, bitter', partsUsed: 'Berries',
    contraindications: 'Avoid during pregnancy. May interact with hormonal medications.', featured: false, active: true,
  },
  {
    name: 'Comfrey Leaf', spanishName: 'Consuelda', latinName: 'Symphytum officinale',
    description: 'Known as "knitbone," comfrey is remarkable for tissue repair, joint support, and reducing inflammation in muscles and connective tissue.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['joint support', 'inflammation', 'recovery', 'muscle tension', 'pain relief', 'skin'],
    energetics: 'Cooling, moistening', taste: 'Slightly sweet, mucilaginous', partsUsed: 'Leaf',
    contraindications: 'For external or short-term internal use only. Avoid during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Cramp Bark', spanishName: 'Corteza Antiespasmos', latinName: 'Viburnum opulus',
    description: 'A powerful antispasmodic herb that relaxes smooth muscle tension. Excellent for menstrual cramps, muscle spasms, and tension.',
    pricePerOunce: 9, inventoryOunces: 16,
    tags: ['cramps', 'pms', 'muscle tension', 'pain relief', 'women hormones', 'nervous system'],
    energetics: 'Cooling', taste: 'Bitter, slightly astringent', partsUsed: 'Bark',
    contraindications: 'Avoid during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Damiana', spanishName: 'Damiana', latinName: 'Turnera diffusa',
    description: 'A warming, uplifting herb traditionally used as an aphrodisiac and mood enhancer. Supports nervous system vitality and feminine energy.',
    pricePerOunce: 6, inventoryOunces: 16,
    tags: ['libido', 'uplifting', 'uplifting mood', 'feminine energy', 'nervine', 'depression', 'anxiety', 'stress', 'energy', 'womb support'],
    energetics: 'Warming', taste: 'Slightly bitter, aromatic', partsUsed: 'Leaf',
    contraindications: 'Avoid during pregnancy. May interact with diabetes medications.', featured: false, active: true,
  },
  {
    name: 'Dandelion Leaf', spanishName: 'Hoja de Diente de León', latinName: 'Taraxacum officinale',
    description: 'A powerhouse nutritive herb rich in minerals. Supports kidney function, acts as a gentle diuretic, and nourishes the whole body.',
    pricePerOunce: 5, inventoryOunces: 24,
    tags: ['kidney', 'urinary', 'detox', 'minerals', 'nutritive', 'nourishing', 'tonic', 'blood purifier', 'digestive bitters'],
    energetics: 'Cooling, slightly bitter', taste: 'Bitter, green', partsUsed: 'Leaf',
    contraindications: 'May interact with diuretic medications.', featured: false, active: true,
  },
  {
    name: 'Dandelion Root', spanishName: 'Raíz de Diente de León', latinName: 'Taraxacum officinale',
    description: 'A premier liver and digestive tonic. Stimulates bile production, supports liver detox, and promotes healthy digestion.',
    pricePerOunce: 9, inventoryOunces: 24,
    tags: ['liver', 'detox', 'digestion', 'digestive bitters', 'bitter', 'gut repair', 'blood purifier', 'kidney'],
    energetics: 'Cooling', taste: 'Bitter, earthy', partsUsed: 'Root',
    contraindications: 'May interact with diuretic medications and blood thinners.', featured: true, active: true,
  },
  {
    name: 'Echinacea', spanishName: 'Equinácea', latinName: 'Echinacea purpurea',
    description: 'The classic immune herb. Stimulates immune function, fights infections, and helps the body recover from colds and flu faster.',
    pricePerOunce: 5, inventoryOunces: 32,
    tags: ['immune', 'cold flu', 'antimicrobial', 'antiviral', 'antibacterial', 'lymphatic', 'lymph support'],
    energetics: 'Cooling', taste: 'Slightly bitter, tingling', partsUsed: 'Root, aerial parts',
    contraindications: 'Avoid with autoimmune conditions. Not for continuous long-term use.', featured: false, active: true,
  },
  {
    name: 'Elderberries', spanishName: 'Saúco', latinName: 'Sambucus nigra',
    description: 'A beloved immune-boosting berry rich in antioxidants. Powerful antiviral properties make it a go-to for cold and flu prevention and recovery.',
    pricePerOunce: 5, inventoryOunces: 32,
    tags: ['immune', 'antiviral', 'cold flu', 'antimicrobial', 'respiratory support'],
    energetics: 'Cooling', taste: 'Sweet, tart, fruity', partsUsed: 'Berries',
    contraindications: 'Raw berries are toxic. Only use properly prepared elderberries.', featured: true, active: true,
  },
  {
    name: 'Elder Flowers', spanishName: 'Flores de Saúco', latinName: 'Sambucus nigra',
    description: 'Gentle and aromatic elder flowers support the respiratory system, ease fevers, and promote healthy skin.',
    pricePerOunce: 8, inventoryOunces: 16,
    tags: ['respiratory support', 'sinus', 'congestion', 'allergies', 'cold flu', 'immune', 'skin', 'fever'],
    energetics: 'Cooling', taste: 'Floral, sweet, slightly musty', partsUsed: 'Flowers',
    contraindications: 'Avoid during pregnancy in large amounts.', featured: false, active: true,
  },
  {
    name: 'Feverfew', spanishName: 'Matricaria', latinName: 'Tanacetum parthenium',
    description: 'A powerful herb for headaches and migraines. Reduces inflammation and prevents migraine onset with regular use.',
    pricePerOunce: 7, inventoryOunces: 16,
    tags: ['headaches', 'migraines', 'inflammation', 'pain relief', 'nervous system'],
    energetics: 'Cooling', taste: 'Very bitter', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy. May interact with blood thinners.', featured: false, active: true,
  },
  {
    name: 'Ginkgo', spanishName: 'Ginkgo', latinName: 'Ginkgo biloba',
    description: 'One of the oldest trees on earth, ginkgo enhances circulation to the brain, improving memory, focus, and cognitive function.',
    pricePerOunce: 4, inventoryOunces: 24,
    tags: ['focus', 'memory', 'brain health', 'cognitive support', 'mental clarity', 'circulation', 'brain fog'],
    energetics: 'Neutral', taste: 'Slightly bitter', partsUsed: 'Leaf',
    contraindications: 'May interact with blood thinners. Avoid before surgery.', featured: false, active: true,
  },
  {
    name: 'Gotu Kola', spanishName: 'Gotu Kola', latinName: 'Centella asiatica',
    description: 'An ancient Ayurvedic herb for the brain and nervous system. Enhances memory, supports meditation, and promotes connective tissue repair.',
    pricePerOunce: 7, inventoryOunces: 16,
    tags: ['brain health', 'memory', 'focus', 'cognitive support', 'nervous system', 'meditation', 'collagen support', 'skin', 'adaptogen'],
    energetics: 'Cooling', taste: 'Slightly bitter, earthy', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy. May interact with sedatives.', featured: false, active: true,
  },
  {
    name: 'Hawthorn Berries', spanishName: 'Bayas de Espino', latinName: 'Crataegus monogyna',
    description: 'Rich in antioxidants and flavonoids, hawthorn berries are a premier heart tonic supporting circulation, cholesterol balance, and heart strength.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['heart', 'circulation', 'blood pressure', 'cholesterol', 'heart opening', 'tonic', 'antioxidant'],
    energetics: 'Slightly warming', taste: 'Tart, slightly sweet', partsUsed: 'Berries',
    contraindications: 'May interact with heart medications.', featured: false, active: true,
  },
  {
    name: 'Hibiscus', spanishName: 'Jamaica / Rosa de Jamaica', latinName: 'Hibiscus sabdariffa',
    description: 'A beautiful ruby-red flower rich in antioxidants and vitamin C. Supports heart health, blood pressure, and kidney function.',
    pricePerOunce: 3, inventoryOunces: 32,
    tags: ['heart', 'blood pressure', 'kidney', 'antioxidant', 'minerals', 'detox', 'immune', 'circulation'],
    energetics: 'Cooling', taste: 'Tart, fruity, cranberry-like', partsUsed: 'Flowers (calyx)',
    contraindications: 'May interact with blood pressure medications.', featured: true, active: true,
  },
  {
    name: 'Hops', spanishName: 'Lúpulo', latinName: 'Humulus lupulus',
    description: 'Famous for its sedative and relaxing properties, hops ease anxiety, insomnia, and nervous tension.',
    pricePerOunce: 7, inventoryOunces: 16,
    tags: ['sleep', 'insomnia', 'deep sleep', 'bedtime', 'anxiety', 'nervine', 'calming', 'relaxation', 'stress'],
    energetics: 'Cooling', taste: 'Very bitter', partsUsed: 'Strobiles (cones)',
    contraindications: 'Avoid with depression. Sedative — avoid with sedative medications.', featured: false, active: true,
  },
  {
    name: 'Horsetail', spanishName: 'Cola de Caballo', latinName: 'Equisetum arvense',
    description: 'One of the richest plant sources of silica. Strengthens hair, nails, bones, and connective tissue.',
    pricePerOunce: 5, inventoryOunces: 16,
    tags: ['hair growth', 'nails', 'collagen support', 'minerals', 'nutritive', 'kidney', 'urinary', 'joint support'],
    energetics: 'Cooling, drying', taste: 'Mild, slightly grassy', partsUsed: 'Aerial parts',
    contraindications: 'Avoid long-term use. Not for kidney disease.', featured: false, active: true,
  },
  {
    name: 'Irish Moss', spanishName: 'Musgo Irlandés', latinName: 'Chondrus crispus',
    description: 'A sea vegetable powerhouse rich in minerals. Supports thyroid health, gut lining, skin hydration, and overall vitality.',
    pricePerOunce: 14, inventoryOunces: 8,
    tags: ['minerals', 'nutritive', 'gut repair', 'skin', 'thyroid', 'tonic', 'nourishing', 'demulcent'],
    energetics: 'Cooling, moistening', taste: 'Mild, oceanic', partsUsed: 'Thallus (whole plant)',
    contraindications: 'Use caution with thyroid medications.', featured: false, active: true,
  },
  {
    name: 'Lavender', spanishName: 'Lavanda', latinName: 'Lavandula angustifolia',
    description: 'A universally beloved herb for calming the nervous system, easing anxiety, supporting sleep, and lifting the mood.',
    pricePerOunce: 5, inventoryOunces: 32,
    tags: ['nervine', 'calming', 'sleep', 'anxiety', 'stress', 'depression', 'relaxation', 'headaches', 'uplifting mood', 'sacred', 'ritual', 'meditation'],
    energetics: 'Cooling', taste: 'Floral, slightly sweet, slightly bitter', partsUsed: 'Flowers',
    contraindications: 'Generally safe. Avoid concentrated essential oil internally.', featured: true, active: true,
  },
  {
    name: 'Lemon Balm', spanishName: 'Melisa / Toronjil', latinName: 'Melissa officinalis',
    description: 'A joyful, uplifting nervine that calms anxiety, supports restful sleep, and brightens the mood.',
    pricePerOunce: 8, inventoryOunces: 24,
    tags: ['nervine', 'calming', 'anxiety', 'stress', 'sleep', 'digestion', 'stomach soothing', 'uplifting', 'uplifting mood', 'depression', 'nervous system'],
    energetics: 'Cooling', taste: 'Lemon, slightly minty, refreshing', partsUsed: 'Aerial parts',
    contraindications: 'May interact with thyroid medications.', featured: true, active: true,
  },
  {
    name: 'Licorice Root', spanishName: 'Regaliz', latinName: 'Glycyrrhiza glabra',
    description: 'A deeply soothing and sweet herb that protects and heals the gut lining, supports adrenal function, and harmonizes herbal formulas.',
    pricePerOunce: 6, inventoryOunces: 24,
    tags: ['gut repair', 'adrenal support', 'digestion', 'demulcent', 'stomach soothing', 'respiratory support', 'throat soothing', 'immune', 'adaptogen'],
    energetics: 'Slightly warming, moistening', taste: 'Very sweet, slightly anise-like', partsUsed: 'Root',
    contraindications: 'Avoid with high blood pressure, kidney disease, or long-term use.', featured: false, active: true,
  },
  {
    name: 'Marshmallow Root', spanishName: 'Raíz de Malvavisco', latinName: 'Althaea officinalis',
    description: 'Exceptional for healing a leaky gut, soothing the urinary tract, and calming dry coughs.',
    pricePerOunce: 6, inventoryOunces: 16,
    tags: ['demulcent', 'gut repair', 'urinary', 'respiratory support', 'throat soothing', 'digestion', 'inflammation', 'IBS'],
    energetics: 'Cooling, moistening', taste: 'Mild, very mucilaginous, slightly sweet', partsUsed: 'Root',
    contraindications: 'May slow absorption of other medications.', featured: false, active: true,
  },
  {
    name: 'Motherwort', spanishName: 'Agripalma', latinName: 'Leonurus cardiaca',
    description: 'A powerful heart and uterine tonic. Calms a racing heart, eases anxiety and palpitations, and supports women\'s reproductive health.',
    pricePerOunce: 4, inventoryOunces: 16,
    tags: ['heart', 'women hormones', 'nervine', 'anxiety', 'pms', 'cramps', 'cycle balance', 'emotional balance', 'nervous system'],
    energetics: 'Cooling', taste: 'Very bitter', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy. Avoid with heart medications.', featured: false, active: true,
  },
  {
    name: 'Mugwort', spanishName: 'Artemisa', latinName: 'Artemisia vulgaris',
    description: 'A sacred dreaming herb used for centuries for vivid dreams, intuition, and spiritual clarity.',
    pricePerOunce: 7, inventoryOunces: 16,
    tags: ['dream support', 'intuition', 'third eye', 'ceremonial', 'sacred', 'ritual', 'digestion', 'women hormones', 'cycle balance', 'meditation'],
    energetics: 'Warming', taste: 'Bitter, aromatic, slightly sage-like', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Mullein', spanishName: 'Gordolobo', latinName: 'Verbascum thapsus',
    description: 'The lung herb. Clears congestion, soothes irritated airways, and supports deep breathing.',
    pricePerOunce: 6, inventoryOunces: 24,
    tags: ['lung', 'respiratory support', 'cough', 'congestion', 'asthma', 'sinus', 'throat soothing'],
    energetics: 'Cooling, slightly moistening', taste: 'Mild, slightly sweet', partsUsed: 'Leaf',
    contraindications: 'Strain tea well to remove fine hairs.', featured: false, active: true,
  },
  {
    name: 'Nettle Leaf', spanishName: 'Ortiga', latinName: 'Urtica dioica',
    description: 'A deeply nutritive herb packed with minerals, vitamins, and protein. Excellent for allergies, anemia, and kidney health.',
    pricePerOunce: 6, inventoryOunces: 32,
    tags: ['minerals', 'nutritive', 'nourishing', 'tonic', 'allergies', 'kidney', 'hair growth', 'blood purifier', 'iron', 'energy'],
    energetics: 'Slightly warming', taste: 'Green, earthy, slightly grassy', partsUsed: 'Leaf',
    contraindications: 'May interact with blood thinners and diabetes medications.', featured: true, active: true,
  },
  {
    name: 'Oat Straw', spanishName: 'Paja de Avena', latinName: 'Avena sativa',
    description: 'A deeply nourishing nervine tonic that rebuilds and feeds the nervous system over time.',
    pricePerOunce: 6, inventoryOunces: 24,
    tags: ['nervine', 'tonic', 'nourishing', 'burnout', 'stress', 'nervous system', 'minerals', 'nutritive', 'chronic fatigue', 'adrenal support'],
    energetics: 'Slightly warming, moistening', taste: 'Mild, slightly sweet, oaty', partsUsed: 'Straw (stems)',
    contraindications: 'Avoid with gluten sensitivity in large amounts.', featured: false, active: true,
  },
  {
    name: 'Passion Flower', spanishName: 'Flor de la Pasión', latinName: 'Passiflora incarnata',
    description: 'A beautiful nervine for anxiety, overactive mind, and insomnia. Calms racing thoughts and promotes deep, restful sleep.',
    pricePerOunce: 9, inventoryOunces: 16,
    tags: ['nervine', 'sleep', 'anxiety', 'insomnia', 'deep sleep', 'bedtime', 'calming', 'stress', 'nervous system regulation', 'overwhelm'],
    energetics: 'Cooling', taste: 'Slightly bitter, mild', partsUsed: 'Aerial parts',
    contraindications: 'May enhance sedative medications. Avoid during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Peppermint', spanishName: 'Menta', latinName: 'Mentha piperita',
    description: 'A refreshing and invigorating herb for digestion, mental clarity, and respiratory health.',
    pricePerOunce: 5, inventoryOunces: 32,
    tags: ['digestion', 'nausea', 'bloating', 'gas', 'stomach soothing', 'mental clarity', 'focus', 'headaches', 'respiratory support', 'energy'],
    energetics: 'Cooling', taste: 'Strongly minty, cooling, refreshing', partsUsed: 'Aerial parts',
    contraindications: 'Avoid with GERD. Keep away from infants\' faces.', featured: true, active: true,
  },
  {
    name: 'Red Raspberry Leaf', spanishName: 'Hoja de Frambuesa Roja', latinName: 'Rubus idaeus',
    description: 'A nutritive tonic for the female reproductive system. Tones the uterus, eases cramps, and supports hormonal balance.',
    pricePerOunce: 3, inventoryOunces: 32,
    tags: ['women hormones', 'womb support', 'cycle balance', 'pms', 'cramps', 'fertility', 'postpartum', 'minerals', 'nutritive', 'tonic'],
    energetics: 'Cooling', taste: 'Mildly astringent, slightly fruity', partsUsed: 'Leaf',
    contraindications: 'Generally safe. Consult before use in early pregnancy.', featured: true, active: true,
  },
  {
    name: 'Rose Petals', spanishName: 'Pétalos de Rosa', latinName: 'Rosa damascena',
    description: 'The flower of love. Rose opens the heart, eases grief, uplifts the spirit, and supports skin health.',
    pricePerOunce: 7, inventoryOunces: 16,
    tags: ['heart opening', 'grief support', 'uplifting', 'uplifting mood', 'feminine energy', 'skin', 'anti-aging', 'sacred', 'ritual', 'emotional balance', 'womb support'],
    energetics: 'Cooling', taste: 'Floral, slightly sweet, astringent', partsUsed: 'Petals',
    contraindications: 'Generally safe.', featured: true, active: true,
  },
  {
    name: 'Rosemary', spanishName: 'Romero', latinName: 'Salvia rosmarinus',
    description: 'An aromatic herb that sharpens memory and focus, stimulates circulation, and lifts the mood.',
    pricePerOunce: 3, inventoryOunces: 32,
    tags: ['memory', 'focus', 'mental clarity', 'circulation', 'brain health', 'energy', 'uplifting', 'digestive bitters', 'hair growth'],
    energetics: 'Warming', taste: 'Pungent, piney, aromatic', partsUsed: 'Aerial parts',
    contraindications: 'Avoid therapeutic amounts during pregnancy.', featured: false, active: true,
  },
  {
    name: 'Sage', spanishName: 'Salvia', latinName: 'Salvia officinalis',
    description: 'A sacred herb of wisdom and purification. Supports cognitive function, eases menopausal hot flashes, and has powerful antimicrobial properties.',
    pricePerOunce: 4, inventoryOunces: 24,
    tags: ['menopause', 'women hormones', 'memory', 'mental clarity', 'antimicrobial', 'throat soothing', 'sacred', 'energetic clearing', 'digestion'],
    energetics: 'Warming, drying', taste: 'Pungent, earthy, slightly bitter', partsUsed: 'Leaf',
    contraindications: 'Avoid during pregnancy and nursing.', featured: false, active: true,
  },
  {
    name: 'Skullcap', spanishName: 'Escutelaria', latinName: 'Scutellaria lateriflora',
    description: 'One of the best nervines for anxiety, tension, and insomnia. Quiets an overactive mind and supports deep relaxation.',
    pricePerOunce: 11, inventoryOunces: 16,
    tags: ['nervine', 'anxiety', 'insomnia', 'sleep', 'stress', 'nervous system', 'calming', 'relaxation', 'bedtime', 'tension', 'overwhelm'],
    energetics: 'Cooling', taste: 'Slightly bitter', partsUsed: 'Aerial parts',
    contraindications: 'May enhance sedative medications.', featured: false, active: true,
  },
  {
    name: 'Slippery Elm', spanishName: 'Olmo Resbaladizo', latinName: 'Ulmus rubra',
    description: 'A deeply soothing demulcent that coats and heals the entire digestive tract. Essential for IBS, leaky gut, and ulcers.',
    pricePerOunce: 8, inventoryOunces: 16,
    tags: ['demulcent', 'gut repair', 'IBS', 'digestion', 'inflammation', 'stomach soothing', 'colon cleanse', 'diarrhea', 'constipation'],
    energetics: 'Cooling, moistening', taste: 'Mild, sweet, mucilaginous', partsUsed: 'Inner bark',
    contraindications: 'May slow absorption of medications.', featured: false, active: true,
  },
  {
    name: 'Spearmint', spanishName: 'Hierba Buena', latinName: 'Mentha spicata',
    description: 'A gentler cousin to peppermint. Also studied for reducing excess androgens, supporting hormonal balance in women.',
    pricePerOunce: 4, inventoryOunces: 24,
    tags: ['digestion', 'gas', 'bloating', 'nausea', 'women hormones', 'cycle balance', 'stomach soothing', 'mental clarity'],
    energetics: 'Slightly cooling', taste: 'Minty, slightly sweet', partsUsed: 'Aerial parts',
    contraindications: 'Generally safe.', featured: false, active: true,
  },
  {
    name: "St. John's Wort", spanishName: 'Hipérico', latinName: 'Hypericum perforatum',
    description: 'The sunshine herb. Lifts depression, eases nerve pain, and supports the nervous system during grief and seasonal changes.',
    pricePerOunce: 5, inventoryOunces: 24,
    tags: ['depression', 'uplifting', 'uplifting mood', 'nervine', 'anxiety', 'grief support', 'pain relief', 'nervous system', 'seasonal'],
    energetics: 'Warming', taste: 'Slightly bitter, resinous', partsUsed: 'Flowering tops',
    contraindications: 'IMPORTANT: Interacts with many medications including antidepressants, birth control, and blood thinners.', featured: false, active: true,
  },
  {
    name: 'Tulsi', spanishName: 'Albahaca Sagrada', latinName: 'Ocimum tenuiflorum',
    description: 'Holy Basil — one of the most sacred plants in Ayurveda. An adaptogen that lifts the spirit, clears the mind, and opens the heart.',
    pricePerOunce: 4, inventoryOunces: 32,
    tags: ['adaptogen', 'stress', 'anxiety', 'uplifting', 'uplifting mood', 'mental clarity', 'immune', 'heart opening', 'sacred', 'ritual', 'nervous system'],
    energetics: 'Warming', taste: 'Spicy, clove-like, slightly sweet', partsUsed: 'Aerial parts',
    contraindications: 'May interact with blood thinners.', featured: true, active: true,
  },
  {
    name: 'Valerian', spanishName: 'Valeriana', latinName: 'Valeriana officinalis',
    description: 'A powerful sedative nervine for insomnia and anxiety. Promotes deep sleep and relaxes muscle tension.',
    pricePerOunce: 12, inventoryOunces: 16,
    tags: ['sleep', 'insomnia', 'deep sleep', 'bedtime', 'anxiety', 'nervine', 'calming', 'muscle tension', 'nervous system regulation'],
    energetics: 'Warming', taste: 'Strongly earthy, somewhat unpleasant', partsUsed: 'Root',
    contraindications: 'Avoid with sedative medications. Some people experience stimulation.', featured: false, active: true,
  },
  {
    name: 'Yarrow', spanishName: 'Milenrama', latinName: 'Achillea millefolium',
    description: 'A warrior herb named after Achilles. Stops bleeding, reduces fever, supports circulation, and has powerful antimicrobial properties.',
    pricePerOunce: 6, inventoryOunces: 24,
    tags: ['circulation', 'immune', 'antimicrobial', 'fever', 'cold flu', 'women hormones', 'cycle balance', 'inflammation', 'alterative'],
    energetics: 'Neutral to slightly cooling', taste: 'Bitter, slightly spicy', partsUsed: 'Aerial parts',
    contraindications: 'Avoid during pregnancy. May interact with blood thinners.', featured: false, active: true,
  },
  {
    name: 'Ginger', spanishName: 'Jengibre', latinName: 'Zingiber officinale',
    description: 'A warming, stimulating root that ignites digestion, improves circulation, eases nausea, and supports immune function.',
    pricePerOunce: 6, inventoryOunces: 32,
    tags: ['digestion', 'nausea', 'stomach soothing', 'circulation', 'immune', 'cold flu', 'inflammation', 'pain relief', 'energy', 'warming'],
    energetics: 'Hot, stimulating', taste: 'Pungent, spicy, warming', partsUsed: 'Root (rhizome)',
    contraindications: 'Use caution with blood thinners and gallstones.', featured: true, active: true,
  },
]

const recipes = [
  {
    name: 'Gut Repair Tea', description: 'A deeply soothing blend to heal and restore the digestive lining, ease inflammation, and support healthy gut flora.',
    tags: ['gut repair', 'digestion', 'IBS', 'inflammation', 'stomach soothing'],
    herbs: [
      { name: 'Marshmallow Root', parts: 2, notes: 'Base demulcent for gut lining' },
      { name: 'Slippery Elm', parts: 2, notes: 'Coats and heals the digestive tract' },
      { name: 'Chamomile', parts: 1, notes: 'Anti-inflammatory and calming' },
      { name: 'Lemon Balm', parts: 1, notes: 'Eases nervous stomach and bloating' },
      { name: 'Ginger', parts: 1, notes: 'Stimulates digestive fire' },
    ],
    instructions: 'Combine herbs. Steep 1 tablespoon per cup in hot (not boiling) water for 10-15 minutes. Drink 2-3 cups daily between meals.',
    featured: true,
  },
  {
    name: 'Hormone Balance Tea', description: 'A nourishing blend to support hormonal harmony, ease PMS and cycle irregularity, and tone the female reproductive system.',
    tags: ['women hormones', 'cycle balance', 'pms', 'fertility', 'womb support'],
    herbs: [
      { name: 'Red Raspberry Leaf', parts: 2, notes: 'Uterine tonic and base herb' },
      { name: 'Chaste Berries', parts: 1, notes: 'Progesterone support and cycle regulation' },
      { name: 'Spearmint', parts: 1, notes: 'Androgen balancing and flavor' },
      { name: 'Rose Petals', parts: 1, notes: 'Heart and womb opening' },
    ],
    instructions: 'Steep 1 tablespoon per cup for 10 minutes. Drink 1-2 cups daily throughout the month.',
    featured: true,
  },
  {
    name: 'Deep Calm Tea', description: 'A classic nervine blend for anxiety, stress, and overwhelm. Quiets the mind and relaxes the body without sedation.',
    tags: ['anxiety', 'stress', 'calming', 'nervous system', 'emotional balance'],
    herbs: [
      { name: 'Lemon Balm', parts: 2, notes: 'Uplifting and calming nervine base' },
      { name: 'Chamomile', parts: 1, notes: 'Gentle relaxant' },
      { name: 'Skullcap', parts: 1, notes: 'Quiets anxious thoughts' },
      { name: 'Lavender', parts: 1, notes: 'Calming and aromatic' },
    ],
    instructions: 'Steep 1 tablespoon per cup for 10 minutes. Drink 1-3 cups daily or as needed during stressful periods.',
    featured: true,
  },
  {
    name: 'Dreamtime Sleep Tea', description: 'A potent sleep blend that relaxes the body, quiets the mind, and invites deep, restorative sleep and vivid dreams.',
    tags: ['sleep', 'insomnia', 'deep sleep', 'bedtime', 'dream support'],
    herbs: [
      { name: 'Valerian', parts: 2, notes: 'Primary sedative nervine' },
      { name: 'Passion Flower', parts: 2, notes: 'Calms racing mind' },
      { name: 'Chamomile', parts: 1, notes: 'Gentle relaxation' },
      { name: 'Mugwort', parts: 1, notes: 'Dream enhancement' },
    ],
    instructions: 'Steep 1 tablespoon per cup for 15 minutes. Drink 30-60 minutes before bed. Add honey to balance the bitter taste.',
    featured: true,
  },
  {
    name: 'Immune Shield Tea', description: 'A powerful immune-boosting blend for cold and flu prevention, recovery, and year-round immune resilience.',
    tags: ['immune', 'cold flu', 'antiviral', 'antimicrobial', 'respiratory support'],
    herbs: [
      { name: 'Elderberries', parts: 2, notes: 'Antiviral powerhouse' },
      { name: 'Echinacea', parts: 1, notes: 'Immune stimulant' },
      { name: 'Ginger', parts: 1, notes: 'Warming and antimicrobial' },
      { name: 'Hibiscus', parts: 1, notes: 'Vitamin C and antioxidants' },
    ],
    instructions: 'Simmer elderberries and ginger for 10 minutes, then add remaining herbs and steep 10 more minutes. Drink 2-3 cups daily at onset of illness.',
    featured: false,
  },
  {
    name: 'Liver Detox Tea', description: 'A cleansing blend to support the liver, promote healthy detox pathways, and purify the blood.',
    tags: ['liver', 'detox', 'blood purifier', 'lymphatic', 'cleanse'],
    herbs: [
      { name: 'Dandelion Root', parts: 2, notes: 'Premier liver tonic' },
      { name: 'Burdock Root', parts: 2, notes: 'Deep blood and liver cleanser' },
      { name: 'Nettle Leaf', parts: 1, notes: 'Nutritive and purifying' },
      { name: 'Ginger', parts: 1, notes: 'Stimulates circulation and detox' },
    ],
    instructions: 'Simmer roots for 15 minutes, add leaf herbs and steep 10 more minutes. Drink 1-2 cups daily, morning or midday.',
    featured: false,
  },
  {
    name: 'Mineral Nourishment Tea', description: 'A daily nourishing tonic rich in bioavailable minerals to replenish deficiencies and build deep vitality.',
    tags: ['minerals', 'nutritive', 'nourishing', 'tonic', 'energy', 'vitality'],
    herbs: [
      { name: 'Nettle Leaf', parts: 3, notes: 'Mineral-rich foundation' },
      { name: 'Oat Straw', parts: 2, notes: 'Silica and B vitamins' },
      { name: 'Red Raspberry Leaf', parts: 1, notes: 'Iron and female tonic' },
      { name: 'Horsetail', parts: 1, notes: 'Silica for hair, nails, bones' },
    ],
    instructions: 'Steep 1-2 tablespoons per cup for 20-30 minutes for maximum mineral extraction. Drink 1-4 cups daily.',
    featured: true,
  },
  {
    name: 'Breath & Lung Tea', description: 'An opening respiratory blend to clear congestion, soothe irritated airways, and support deep healthy breathing.',
    tags: ['respiratory support', 'lung', 'cough', 'congestion', 'asthma', 'sinus'],
    herbs: [
      { name: 'Mullein', parts: 2, notes: 'The primary lung herb' },
      { name: 'Licorice Root', parts: 1, notes: 'Soothes airway inflammation' },
      { name: 'Peppermint', parts: 1, notes: 'Opens airways' },
      { name: 'Ginger', parts: 1, notes: 'Warming and stimulating' },
    ],
    instructions: 'Steep 1 tablespoon per cup for 10-15 minutes. Inhale the steam as you sip. Drink 3-4 cups daily for acute respiratory issues.',
    featured: false,
  },
]

export async function GET() {
  try {
    // Check if already seeded
    const count = await prisma.herb.count()
    if (count > 0) {
      return NextResponse.json({ message: `Already seeded! ${count} herbs in database.` })
    }

    // Seed herbs
    for (const herb of herbs) {
      await prisma.herb.create({ data: herb })
    }

    // Seed recipes
    for (const recipe of recipes) {
      await prisma.recipe.create({ data: recipe })
    }

    return NextResponse.json({
      success: true,
      message: `✅ Seeded ${herbs.length} herbs and ${recipes.length} recipes successfully!`
    })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({ error: String(error) }, { status: 500 })
  }
}
